PURGE RECYCLEBIN;
/SET SERVEROUTPUT ON;/
declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='STATE';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE STATE';
    END IF;
END;
/
declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='PARTY';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE PARTY';
    END IF;
END;
/

CREATE TABLE STATE(
STATE_ID INT NOT NULL PRIMARY KEY, 
STATE_NAME VARCHAR(255) UNIQUE NOT NULL ); 

CREATE TABLE PARTY(
PARTY_ID INT NOT NULL PRIMARY KEY, 
PARTY_NAME VARCHAR(255) UNIQUE NOT NULL , 
PARTY_ADDRESS VARCHAR(255) UNIQUE NOT NULL, 
CONTACT_NUMBER VARCHAR(255) UNIQUE NOT NULL, 
EMAIL VARCHAR(255) UNIQUE NOT NULL); 

Insert into STATE Values(1,'TELANGANA')	;
Insert into STATE Values(2,'MAHARASTRA');

Insert into PARTY values(1,'SHIVSENA','MUMBAI','1234567890','SENA@SENA.COM');
Insert into PARTY values(2,'BJP','AMBEBAD','2345678910','BJP@BJP.COM');
Insert into PARTY values(3,'CONGRESS','DELHI','2835678901','CNG@CNG.COM');


